_target_ : src.model.trainer.Trainer
data: ./data/heart_cleveland_upload.csv
model:
    - scaler:
        _target_: sklearn.preprocessing.StandardScaler
    - model:
        _target_: sklearn.svm.SVC
        kernel: poly
save_to: ./models/svc.pkl
accuracy_on_train:
    metrics:  [accuracy_score, f1_score]
