trainer:
    _target_ : src.model.trainer.Trainer
    data: ./data/heart_cleveland_upload.csv
    model: 
        _target_: sklearn.linear_model.LogisticRegression
        solver: liblinear
    save_to: ./models/logistic_regresson.pkl
    accuracy_on_train:
        metrics:  [accuracy_score, f1_score]
