apiVersion: v1
kind: Pod
metadata:
  name: online-inference-pod
spec:
  containers:
    - name: ml-in-prod
      image: yehudaitkin/ml-in-prod::latest
      imagePullPolicy: Always
      ports:
      - name: online-inference
        containerPort: 5000
        protocol: TCP
