apiVersion: v1
kind: Pod
metadata:
  name: ml-in-prod-inference
spec:
  containers:
  - name: inference
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 20
      periodSeconds: 100
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
